#JDBC Properties
#For Oracle DB (fixed keys)
spring: 
   datasource: 
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: mohitdb
      password: mohitdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 100
         keepalive-times: 100000



