#JDBC Properties
#For Oracle DB (fixed keys)
spring: 
   datasource: 
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: mohitdb
      password: mohitdb
      oracleucp: 
         min-pool-size: 10
         max-pool-size: 100
         time-to-live-connection-timeout: 100000

#Specify the dataSource type
      type: oracle.ucp.jdbc.PoolDataSourceImpl